#cloud-config

hostname: debian

timezone: Asia/Tokyo

package_update: true
package_upgrade: true

runcmd:
  - |
    export DEBIAN_FRONTEND=noninteractive

    apt-get update
    apt-get install -y curl

    PROFILE=full \ 
    SSH_PUBKEY="YOUR_PUBLIC_KEY" \
    SSH_PASSWORD="YOUR_PASSWORD" \
    ENABLE_NOPASSWD=true \
    bash <(curl -fsSL https://raw.githubusercontent.com/mottzz87/debian-setup/main/install.sh)

final_message: "✅ cloud-init finished"