[Definition]

failregex = <HOST> -.*"(GET|POST).*\.(php|asp|aspx|jsp).*" (404|444|500)
            <HOST> -.*"(GET|POST).*/wp-.*" (404|444)
            <HOST> -.*"(GET|POST).*/\.env.*"
            <HOST> -.*"(GET|POST).*/\.git.*"
            <HOST> -.*"(GET|POST).*(cmd=|exec=|shell=).*"
            <HOST> -.*"Go-http-client

ignoreregex =