[Definition]

failregex = <HOST> -.*"(GET|POST).*\.env
            <HOST> -.*"(GET|POST).*\.git
            <HOST> -.*"(GET|POST).*(phpmyadmin|pma)
            <HOST> -.*"(GET|POST).*wp-login
            <HOST> -.*"(GET|POST).*xmlrpc
            <HOST> -.*"(GET|POST).*\.sql
            <HOST> -.*"(GET|POST).*\.bak
            <HOST> -.*"(GET|POST).*\.log

ignoreregex =