server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    access_log off;
    log_not_found off;

    return 444;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name _;

    access_log off;
    log_not_found off;

    ssl_reject_handshake on;
}